AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false

Layout/LineLength:
  Max: 110
  Exclude: ["*.gemspec"]

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Metrics/AbcSize:
  Max: 20
  Exclude: ["spec/**/*"]

Metrics/BlockLength:
  Exclude: ["spec/**/*", "*.gemspec"]

Metrics/MethodLength:
  Max: 15
  Exclude: ["spec/**/*"]

Style/CaseLikeIf:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Exclude: ["gemfiles/*"]

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Exclude: ["spec/**/*", "*.gemspec", "Rakefile"]

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
