sudo: false
language: ruby
env:
  - COVERALLS_PARALLEL=true
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
gemfile:
  - gemfiles/activerecord_5.gemfile
  - gemfiles/rails.gemfile
  - gemfiles/faker.gemfile
  - gemfiles/ffaker.gemfile
services:
  - postgresql
notifications:
  webhooks: https://coveralls.io/webhook
before_install: "gem update --system && gem install bundler"
before_script:
  - psql -c 'create database test;' -U postgres
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - cp config/database.yml.travis config/database.yml
script: "bundle exec rake"
