version: "3.9"
services:
  postgres:
    image: postgres:11
    ports:
      - "2345:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
  mysql:
    image: mysql:5
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
