postgres:
  adapter: "postgresql"
  host: "127.0.0.1"
  port: "2345"
  database: "test"
  username: "test"
  password: "test"

sqlite3:
  adapter: "sqlite3"
  database: ":memory:"

mysql:
  adapter: "mysql2"
  host: "127.0.0.1"
  port: "3306"
  database: "test"
  username: "test"
  password: "test"
